name: Deploy Customer Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/services/customer-service/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::343218212829:role/GitHubActionsDeployLambda
          aws-region: us-east-1

      - name: Who am I in AWS?
        run: aws sts get-caller-identity

      - name: Build Lambda zip
        run: |
          cd backend/services/customer-service
          npm ci
          zip -r lambda.zip .

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name customer-service \
            --zip-file fileb://backend/services/customer-service/lambda.zip
